#!/bin/bash

if [[ -z $1 ]] ; then
	echo "Error: missing parameter (yml file)"
	exit 1
fi

SCRIPT="/scripts/$1"
if [[ ! -r $SCRIPT ]] ; then
	echo "Error: file '$SCRIPT' is not readable"
	exit 1
fi

echo Preparing docker container...
echo

apt-get update -qq
apt-get install -y -qq tmux libyaml-tiny-perl > /dev/null

echo
echo Preparing finished. Proceeding now...
echo
sleep 1

tmux new-session -d
tmux split-window -v
tmux split-window -h
tmux resize-pane -t 0:0.1 -D 4
tmux resize-pane -t 0:0.1 -R 10

cp "$SCRIPT" /tmp/testenv_script.yml

tmux send-keys -t 0:0.1 '/bin/perl /scripts/controller ; sleep 5 ; tmux kill-session' Enter
tmux send-keys -t 0:0.2 '/bin/perl /scripts/show-status' Enter
tmux a
