#!/bin/bash

function log {
    echo $* > status
}

log "Preparing tmux..."

tmux new-window
tmux split-window -v -l 2 "watch --no-title cat status"
tmux split-window -v -t 0
sleep 1
tmux split-window -h -t 0
tmux split-window -h -t 2
sleep 1

echo Hello

#tmux select-window -t 0:0

log "Connecting to all 4 VMs..."

tmux send-keys -t 0:1.0 'vagrant ssh master' Enter
tmux send-keys -t 0:1.1 'vagrant ssh node1' Enter
tmux send-keys -t 0:1.2 'vagrant ssh node2' Enter
tmux send-keys -t 0:1.3 'vagrant ssh node3' Enter

sleep 3

for panel in $( seq 0 3 ) ; do
    tmux send-keys -t 0:1.$panel 'ip a | grep 192.168.56.' Enter
done

sleep 1

for panel in $( seq 1 3 ) ; do
    tmux send-keys -t 0:1.$panel 'ping -c 20 192.168.56.10' Enter
done

sleep 5

tmux send-keys -t 0:1.0 'sudo iptables -I INPUT -p icmp -j DROP' Enter
tmux send-keys -t 0:1.0 'sudo iptables -L -n -v --line-numbers' Enter

sleep 5

tmux send-keys -t 0:1.0 'sudo iptables -L -n -v --line-numbers' Enter
tmux send-keys -t 0:1.0 'sudo iptables -F' Enter

sleep 5

tmux send-keys -t 0:1.0 'sudo iptables -I INPUT -p icmp -s 192.168.56.12 -j DROP' Enter
tmux send-keys -t 0:1.0 'sudo iptables -L -n -v --line-numbers' Enter

sleep 5

tmux send-keys -t 0:1.0 'sudo iptables -L -n -v --line-numbers' Enter
tmux send-keys -t 0:1.0 'sudo iptables -F' Enter

sleep 10

for panel in $( seq 0 3 ) ; do
    tmux send-keys -t 0:1.$panel 'exit' Enter
done
#tmux send-keys -t 0:1.1 'exit' Enter
#tmux send-keys -t 0:1.2 'exit' Enter
#tmux send-keys -t 0:1.3 'exit' Enter

sleep 5

tmux kill-window
