# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "debian/bullseye64"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "192.168.56.10"
    subconfig.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y mosquitto
     echo 'listener 1883 0.0.0.0' > /etc/mosquitto/conf.d/tutorial.conf
     echo 'allow_anonymous true' >> /etc/mosquitto/conf.d/tutorial.conf
     systemctl restart mosquitto
    SHELL
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "192.168.56.#{i + 10}"
      subconfig.vm.provision "shell", inline: <<-SHELL
       apt-get update
       apt-get install -y mosquitto-clients
      SHELL
    end
  end

end
