# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provision "shell", inline: <<-SHELL
   apt-get update
   apt-get install -y restic jq tree
  SHELL
end
